tests/tcg/multiarch: add fp-test into multiarch set
The compile for fp-test is a little funky as we need to include a
build of QEMU's softfloat as well. There is still a problem caused by
the inclusion of config-host.h by osdep.h as it will trigger problems
like:

  In file included from /home/alex/lsrc/qemu/qemu.git/include/qemu/bitops.h:16:0,
                   from /home/alex/lsrc/qemu/qemu.git/fpu/softfloat.c:87:
  /home/alex/lsrc/qemu/qemu.git/include/qemu/host-utils.h: In function ‘mulu64’:
  /home/alex/lsrc/qemu/qemu.git/include/qemu/host-utils.h:35:5: error: unknown type name ‘__uint128_t’
       __uint128_t r = (__uint128_t)a * b;
     ^

When trying to cross build i386 on an x86_64 host.

Signed-off-by: Alex Bennée <alex.bennee@linaro.org>
Message-Id: <20180419135901.30035-42-alex.bennee@linaro.org>
Acked-by: Fam Zheng <famz@redhat.com>