scripts/checkpatch.pl: Bug fix
Bug fix: checkpatch.pl stops complaining about following pattern:
"""
do {
    //do somethins;
} while (conditions);
"""

Two things need to be mentioned:
1) Before I casue this bug, checkpatch.pl will raise a wrong
complain:
"""
ERROR: braces {} are necessary even for single statement blocks
+    for (i == 0; i < 0; ++i)
+    {
+        ;
+    } else
"""
In this patch, this wrong complain get fixed.

2) Becasue all(`if`, `while`, `for`) check have been done in this
`if` block(Line: 2356), and this block contains following statement:
""" Line: 2379
$suppress_ifbraces{$ln + $offset} = 1;
"""
So the block after this block may never run:
""" Line: 2415
if (!defined $suppress_ifbraces{$linenr - 1} &&
	$line =~ /\b(if|while|for|else)\b/ &&
	$line !~ /\#\s*if/ &&
	$line !~ /\#\s*else/) {
"""
But I think, maybe it's ok, becasue all check has been done by
up block. I'm not sure, please give me some advice.

Signed-off-by: Su Hang <suhang16@mails.ucas.ac.cn>
Message-Id: <1521114316-19980-1-git-send-email-suhang16@mails.ucas.ac.cn>